server:
  port: 8081
spring:
  servlet:
    multipart:
      max-file-size: 10MB
  # Spring Security Default user name and password
  security:
    user:
      roles: ADMIN
      name: actuator
      password: actuator
  redis:
    host: localhost
    port: 6379
management:
  endpoints:
    web:
      exposure:
        include=*: